### ISSUE TITLE
System.exit(0)

### ISSUE THREAD

**Issue by george-bisiarin** [nik1811e/football.statistic.parser#1]
https://github.com/nik1811e/football-statistic-parser/blob/6b41d2c46f557c7878cf5031a5fd0f84d2954e8c/src/main/java/io/zensoft/neliseenko/football/statistic/parser/handlers/InputHandler.java#L44

1. Как тестировать этот кусок кода, если System.exit(0) оставить? Как на юнит тесте понять, что все корректно работает?
2. В более сложных кейсах, например, в многопоточных приложениях в одном потоке вызвался данный оператор, что будет с остальными потоками? Возможен ли риск некоторой потери данных или приведения их в неконсистентное состояние прерванным потоком, который с этими данными работал?

**Comment by nik1811e** [comment]
1. ExpectedSystemExit. Проверяет был ли вызван exit(...). 
Можно также реализовать два класса имплементирующих интерфейс с exit(...), как вариант, один выполняет эту функцию , второй для теста , который вернёт буль. 
2. Если оставить в многопоточном приложении подобный кусок кода, то при вызове exit(...) завершится не текущий поток, а JVM, при этом все запущенные потоки завершаться и данные могут быть нарушены, что приведет к ошибкам.
